# Generated by Django 5.0.14 on 2026-06-10 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scraping', 'Scraping'), ('scraped', 'Scraped'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('scraped_data', models.JSONField(blank=True, null=True)),
                ('error_msg', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='companies.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
