# Generated by Django 5.0.14 on 2026-06-10 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=64)),
                ('prompt_text', models.TextField()),
                ('response_text', models.TextField()),
                ('tokens_in', models.PositiveIntegerField()),
                ('tokens_out', models.PositiveIntegerField()),
                ('cost_usd', models.FloatField()),
                ('latency_ms', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_calls', to='companies.company')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_calls', to='companies.source')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
