# Generated by Django 5.0.14 on 2026-06-10 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_pipelinerun'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydna',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DNAFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='companies.companydna')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
