# Generated by Django 5.0.14 on 2026-06-11 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_companydna_confidence_score_dnafeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companydna',
            name='is_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SectionApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(choices=[('chi_siamo', 'Chi siamo'), ('mission', 'Mission'), ('settore', 'Settore'), ('mercato', 'Mercato'), ('pilastri', 'Pilastri')], max_length=20)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_clarification', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_approvals', to='companies.companydna')),
            ],
            options={
                'ordering': ['-approved_at'],
                'unique_together': {('dna', 'section_key')},
            },
        ),
    ]
