# Generated by Django 5.0.14 on 2026-06-11 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_companydna_is_approved_sectionapproval'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sectionapproval',
            unique_together=set(),
        ),
    ]
