# Generated by Django 5.0.14 on 2026-06-12 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_sectionapproval_remove_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companydna',
            name='dna_type',
            field=models.CharField(choices=[('pre', 'Pre-DNA'), ('complete', 'DNA completo')], default='pre', max_length=20),
        ),
        migrations.CreateModel(
            name='CompanyFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('content_text', models.TextField()),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_files', to='companies.company')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('plan_slug', models.CharField(default='starter', max_length=20)),
                ('section_key', models.CharField(default='pilastri', max_length=20)),
                ('principle', models.CharField(max_length=120)),
                ('question', models.TextField()),
                ('answer_depth', models.CharField(default='generica', max_length=40)),
                ('answer_guidance', models.TextField(blank=True)),
                ('answer', models.TextField(blank=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_questions', to='companies.company')),
                ('dna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='companies.companydna')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='companyquestion',
            constraint=models.UniqueConstraint(fields=('dna', 'code'), name='unique_company_question_per_dna_code'),
        ),
    ]
