# Generated by Django 5.0.14 on 2026-06-16 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_companydna_dna_type_companyfile_companyquestion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='companies.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductDNA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('dna_type', models.CharField(choices=[('pre', 'Pre-DNA'), ('complete', 'DNA completo')], default='pre', max_length=20)),
                ('content', models.JSONField()),
                ('is_current', models.BooleanField(default=True)),
                ('is_approved', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dna_versions', to='companies.product')),
            ],
            options={
                'verbose_name': 'Product DNA',
                'verbose_name_plural': 'Product DNAs',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='ProductFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('content_text', models.TextField()),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_files', to='companies.product')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('plan_slug', models.CharField(default='starter', max_length=20)),
                ('section_key', models.CharField(default='valore', max_length=20)),
                ('principle', models.CharField(max_length=120)),
                ('question', models.TextField()),
                ('answer_depth', models.CharField(default='generica', max_length=40)),
                ('answer_guidance', models.TextField(blank=True)),
                ('answer', models.TextField(blank=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='companies.productdna')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_questions', to='companies.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductSectionApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(choices=[('descrizione', 'Descrizione'), ('applicazione', 'Applicazione'), ('specifiche', 'Specifiche'), ('vincoli', 'Vincoli'), ('valore', 'Valore')], max_length=20)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_clarification', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_approvals', to='companies.productdna')),
            ],
            options={
                'ordering': ['-approved_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('company', 'slug'), name='unique_product_slug_per_company'),
        ),
        migrations.AddConstraint(
            model_name='productdna',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('product', 'is_current'), name='unique_current_product_dna_per_product'),
        ),
        migrations.AddConstraint(
            model_name='productquestion',
            constraint=models.UniqueConstraint(fields=('dna', 'code'), name='unique_product_question_per_dna_code'),
        ),
    ]
