# Generated by Django 5.0.14 on 2026-06-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_product_productdna_productfile_productquestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyquestion',
            name='section_key',
            field=models.CharField(default='logica_decisionale', max_length=20),
        ),
        migrations.AlterField(
            model_name='sectionapproval',
            name='section_key',
            field=models.CharField(choices=[('identita', 'Chi siamo e come ci poniamo'), ('modelli_mentali', 'Come ragioniamo'), ('nucleo_tecnico', 'Cosa ci rende unici'), ('confini', 'I nostri confini'), ('tono', 'Il nostro tono'), ('logica_decisionale', 'Come prendiamo decisioni')], max_length=20),
        ),
    ]
