# Generated by Django 5.0.14 on 2026-06-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_alter_companyquestion_section_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyquestion',
            name='pool',
            field=models.CharField(choices=[('template', 'Template-anchored'), ('kb_anchored', 'KB-anchored')], default='template', max_length=20),
        ),
    ]
