# Generated by Django 5.0.14 on 2026-06-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_purge_old_dna_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydna',
            name='audit_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='companydna',
            name='previous_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
