# Generated by Django 5.0.14 on 2026-06-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_companydna_audit_hash_companydna_previous_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydna',
            name='_enrichment',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
