# Generated by Django 6.0.6 on 2026-06-29 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_companyquestion_gap_round_and_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productquestion',
            options={'ordering': ['question_round', 'id']},
        ),
        migrations.AddField(
            model_name='product',
            name='codice',
            field=models.CharField(blank=True, help_text='Codice interno dello specialista, es: CI-001', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('bozza', 'Bozza'), ('in_costruzione', 'In Costruzione'), ('in_validazione', 'In Validazione'), ('attivo', 'Attivo'), ('archiviato', 'Archiviato')], default='bozza', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='tipologia',
            field=models.CharField(blank=True, help_text='Es: canale, vasca, piastrini, copricanale', max_length=100),
        ),
        migrations.AddField(
            model_name='productdna',
            name='_enrichment',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productdna',
            name='audit_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='productdna',
            name='previous_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='productquestion',
            name='parent_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='companies.productquestion'),
        ),
        migrations.AddField(
            model_name='productquestion',
            name='pool',
            field=models.CharField(choices=[('template', 'Template'), ('kb_anchored', 'KB Anchored')], default='template', max_length=20),
        ),
        migrations.AddField(
            model_name='productquestion',
            name='question_round',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='productquestion',
            name='section_key',
            field=models.CharField(default='logica_decisionale', max_length=20),
        ),
        migrations.AlterField(
            model_name='productsectionapproval',
            name='section_key',
            field=models.CharField(choices=[('identita', 'Chi siamo e come ci poniamo'), ('modelli_mentali', 'Come ragioniamo'), ('nucleo_tecnico', 'Cosa ci rende unici'), ('confini', 'I nostri confini'), ('tono', 'Il nostro tono'), ('logica_decisionale', 'Come prendiamo decisioni')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('company', 'codice'), name='unique_product_code_per_company'),
        ),
    ]
