# Generated by Django 5.0.14 on 2026-06-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_product_specialista_lifecycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productquestion',
            name='section_key',
            field=models.CharField(default='identita_tecnica', max_length=20),
        ),
        migrations.AlterField(
            model_name='productsectionapproval',
            name='section_key',
            field=models.CharField(choices=[('identita_tecnica', 'Identità del prodotto'), ('architettura', 'Architettura & componenti'), ('specifiche', 'Specifiche & parametri'), ('applicazione', 'Processo & installazione'), ('vincoli', 'Vincoli & limiti operativi'), ('configurazione', 'Logica di configurazione')], max_length=20),
        ),
    ]
