# Generated by Django 5.0.14 on 2026-06-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0017_alter_productquestion_section_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cliente_diretto',
            field=models.CharField(blank=True, choices=[('b2b_tecnico', 'B2B con professionisti tecnici'), ('b2b_non_tecnico', 'B2B con buyer non tecnici'), ('b2b2c', 'B2B2C'), ('b2c', 'B2C')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='contesto_libero',
            field=models.TextField(blank=True, default='', help_text='Cosa un nuovo cliente dovrebbe capire prima di lavorare con voi, che non trova sul sito'),
        ),
        migrations.AddField(
            model_name='company',
            name='custom_frequenza',
            field=models.CharField(blank=True, choices=[('sistematico', 'Sì, sistematicamente'), ('raramente', 'Sì, raramente'), ('mai', 'No, mai')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='company',
            name='installatori_in_filiera',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='prodotto_fisico',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='settore_primario',
            field=models.CharField(blank=True, choices=[('beni_fisici', 'Produzione di beni fisici'), ('lavorazione_materiali', 'Trasformazione/lavorazione materiali'), ('installazione_posa', 'Installazione/posa'), ('servizi_professionali', 'Servizi professionali'), ('software_saas', 'Software/SaaS'), ('distribuzione_commercio', 'Distribuzione/commercio'), ('formazione_consulenza', 'Formazione/consulenza')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='company',
            name='settore_secondario',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
