# Generated by Lex on 2026-07-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0018_company_cliente_diretto_company_contesto_libero_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsistencyIssue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("scope", models.CharField(choices=[("periodic", "Audit periodico"), ("specialist", "Audit specialista")], max_length=20)),
                ("issue_type", models.CharField(blank=True, max_length=40)),
                ("severity", models.CharField(choices=[("low", "Bassa"), ("medium", "Media"), ("high", "Alta")], default="medium", max_length=10)),
                ("status", models.CharField(choices=[("open", "Aperta"), ("ignored", "Ignorata"), ("resolved", "Risolta"), ("archived", "Archiviata")], default="open", max_length=12)),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField()),
                ("recommendation", models.TextField(blank=True)),
                ("company_layer", models.CharField(blank=True, max_length=30)),
                ("product_layer", models.CharField(blank=True, max_length=30)),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="consistency_issues", to="companies.company")),
                ("company_dna", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="consistency_issues", to="companies.companydna")),
                ("product", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="consistency_issues", to="companies.product")),
                ("product_dna", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="consistency_issues", to="companies.productdna")),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["company", "status", "scope"], name="companies_c_company_a42e39_idx"),
                    models.Index(fields=["company", "severity", "status"], name="companies_c_company_4e194d_idx"),
                ],
            },
        ),
    ]
