# Generated by Django 5.0.14 on 2026-07-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0022_product_generation_step"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyquestion",
            name="suggested_answers",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
