# Generated by Django 5.0.14 on 2026-07-27 08:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0024_agentconversation_agentmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # State-only rename: physical tables companies_product / companies_companydna
        # are preserved via Meta.db_table, so no DDL must run (verified with
        # sqlmigrate: zero statements). The canonical pattern for this is
        # SeparateDatabaseAndState with empty database_operations.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameModel(
                    old_name='CompanyDNA',
                    new_name='DNAGenerale',
                ),
                migrations.RenameModel(
                    old_name='Product',
                    new_name='Specialista',
                ),
                migrations.AlterModelTable(
                    name='dnagenerale',
                    table='companies_companydna',
                ),
                migrations.AlterModelTable(
                    name='specialista',
                    table='companies_product',
                ),
            ],
        ),
    ]
