# Generated by Django 5.0.14 on 2026-07-27 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0025_rename_companydna_dnagenerale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentmessage',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='agentmessage',
            name='llm_call',
        ),
        migrations.DeleteModel(
            name='AgentConversation',
        ),
        migrations.DeleteModel(
            name='AgentMessage',
        ),
    ]
