# Generated by Django 5.0.14 on 2026-08-10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0026_delete_agentconversation_agentmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="codice_fiscale",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="company",
            name="email_contatto",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="company",
            name="nome_commerciale",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="company",
            name="partita_iva",
            field=models.CharField(blank=True, default="", max_length=11),
        ),
        migrations.AddField(
            model_name="company",
            name="pec",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="company",
            name="rea",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="company",
            name="sito_web",
            field=models.URLField(blank=True, default="", max_length=2048),
        ),
        migrations.AddField(
            model_name="productquestion",
            name="suggested_answers",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="CompanyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("phone", "Telefono"), ("whatsapp", "WhatsApp")],
                        max_length=12,
                    ),
                ),
                ("value", models.CharField(max_length=40)),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="companies.company",
                    ),
                ),
            ],
            options={"ordering": ["kind", "position", "id"]},
        ),
        migrations.CreateModel(
            name="CompanySocial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("network", models.CharField(max_length=80)),
                ("url", models.URLField(max_length=2048)),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_profiles",
                        to="companies.company",
                    ),
                ),
            ],
            options={"ordering": ["position", "id"]},
        ),
    ]
