# Generated by Django 5.0.14 on 2026-06-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_company_files_mb_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='max_product_files_mb',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='plan',
            name='unlimited_product_files',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspacesubscription',
            name='product_files_bytes_used',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
