# Generated by Django 5.0.14 on 2026-08-12 15:20

from django.db import migrations, models


def invalidate_parent_domain_sessions(apps, schema_editor):
    """Captured legacy session keys must not survive the host-only rollout."""
    if getattr(schema_editor.connection, "schema_name", "public") != "public":
        return
    session = apps.get_model("sessions", "Session")
    session.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_plan_max_product_files_mb_and_more'),
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHandoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('tenant_schema', models.CharField(max_length=63)),
                ('user_id', models.BigIntegerField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RunPython(
            invalidate_parent_domain_sessions,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
